(function($){"use strict";CherryJsCore.utilites.namespace('theme_script');CherryJsCore.theme_script={init:function(){var self=this;if(CherryJsCore.status.is_ready){self.document_ready_render(self);}else{CherryJsCore.variable.$document.on('ready',self.document_ready_render(self));}
if(CherryJsCore.status.on_load){self.window_load_render(self);}else{CherryJsCore.variable.$window.on('load',self.window_load_render(self));}},document_ready_render:function(self){var self=self;self.swiper_carousel_init(self);self.post_formats_custom_init(self);self.navbar_init(self);self.search_trigger(self);self.subscribe_init(self);self.main_menu(self,$('.main-navigation'));self.to_top_init(self);self.widget_classes_init(self);self.full_height(self);self.mobile_menu(self);},window_load_render:function(self){var self=self;self.page_preloader_init(self);},getTransitionEnd:function(){var styles=Object.keys(document.body.style),transition='transitionend',transitions={'transition':'transitionend','OTransition':'oTransitionEnd','MozTransition':'transitionend','WebkitTansition':'webkitTransitionEnd'};Object.keys(transitions).forEach(function(key){if(-1<styles.indexOf(key)){transition=transitions[key];}});return transition;},debounce:function(callback,threshold){var _timeout;return function _debounced($jqEvent){function _delayed(){callback();timeout=null;}
if(_timeout){clearTimeout(_timeout);}
_timeout=setTimeout(_delayed,threshold);};},swiper_carousel_init:function(self){jQuery('.autoclean-carousel').each(function(){var swiper=null,uniqId=jQuery(this).data('uniq-id'),slidesPerView=parseFloat(jQuery(this).data('slides-per-view')),slidesPerGroup=parseFloat(jQuery(this).data('slides-per-group')),slidesPerColumn=parseFloat(jQuery(this).data('slides-per-column')),spaceBetweenSlides=parseFloat(jQuery(this).data('space-between-slides')),durationSpeed=parseFloat(jQuery(this).data('duration-speed')),swiperLoop=jQuery(this).data('swiper-loop'),freeMode=jQuery(this).data('free-mode'),grabCursor=jQuery(this).data('grab-cursor'),mouseWheel=jQuery(this).data('mouse-wheel'),breakpointsSettings={1200:{slidesPerView:Math.floor(slidesPerView*0.75),spaceBetween:Math.floor(spaceBetweenSlides*0.75)},992:{slidesPerView:Math.floor(slidesPerView*0.5),spaceBetween:Math.floor(spaceBetweenSlides*0.5)},769:{slidesPerView:(0!==Math.floor(slidesPerView*0.25))?Math.floor(slidesPerView*0.25):1},};if(1==slidesPerView){breakpointsSettings={}}
var swiper=new Swiper('#'+uniqId,{slidesPerView:slidesPerView,slidesPerGroup:slidesPerGroup,slidesPerColumn:slidesPerColumn,spaceBetween:spaceBetweenSlides,speed:durationSpeed,loop:swiperLoop,freeMode:freeMode,grabCursor:grabCursor,mousewheelControl:mouseWheel,paginationClickable:true,nextButton:'#'+uniqId+'-next',prevButton:'#'+uniqId+'-prev',pagination:'#'+uniqId+'-pagination',onInit:function(){$('#'+uniqId+'-next').css({'display':'block'});$('#'+uniqId+'-prev').css({'display':'block'});},breakpoints:breakpointsSettings});});},post_formats_custom_init:function(self){CherryJsCore.variable.$document.on('cherry-post-formats-custom-init',function(event){if('slider'!==event.object){return;}
var uniqId='#'+event.item.attr('id'),swiper=new Swiper(uniqId,{pagination:uniqId+' .swiper-pagination',paginationClickable:true,nextButton:uniqId+' .swiper-button-next',prevButton:uniqId+' .swiper-button-prev',spaceBetween:30,onInit:function(){$(uniqId+' .swiper-button-next').css({'display':'block'});$(uniqId+' .swiper-button-prev').css({'display':'block'});},});event.item.data('initalized',true);});var items=[];$('.mini-gallery .post-thumbnail__link').on('click',function(event){event.preventDefault();$(this).parents('.mini-gallery').find('.post-gallery__slides > a[href]').each(function(){items.push({src:$(this).attr('href'),type:'image'});});$.magnificPopup.open({items:items,gallery:{enabled:true}});});},navbar_init:function(self){$(window).load(function(){var $navbar=$('.main-navigation');if(!$.isFunction(jQuery.fn.stickUp)||!$navbar.length){return!1;}
$navbar.stickUp({correctionSelector:'#wpadminbar',listenSelector:'.listenSelector',pseudo:true,active:true});CherryJsCore.variable.$document.trigger('scroll.stickUp');});},search_trigger:function(self){var toggle=$('.search__toggle'),container=$('.top-panel__wrap'),field=$('.header__search .search-form__field');toggle.on('click',function(){container.toggleClass('srch-on');field.focus();}).on('click touchstart touchend');if(container.hasClass('srch-on')){container.removeClass('srch-on');}},subscribe_init:function(self){CherryJsCore.variable.$document.on('click','.subscribe-block__submit',function(event){event.preventDefault();var $this=$(this),form=$this.parents('form'),nonce=form.find('input[name="nonce"]').val(),mail_input=form.find('input[name="subscribe-mail"]'),mail=mail_input.val(),error=form.find('.subscribe-block__error'),success=form.find('.subscribe-block__success'),hidden='hidden';if(''===mail){mail_input.addClass('error');return!1;}
if($this.hasClass('processing')){return!1;}
$this.addClass('processing');error.empty();if(!error.hasClass(hidden)){error.addClass(hidden);}
if(!success.hasClass(hidden)){success.addClass(hidden);}
$.ajax({url:autoclean.ajaxurl,type:'post',dataType:'json',data:{action:'autoclean_subscribe',mail:mail,nonce:nonce},error:function(){$this.removeClass('processing');}}).done(function(response){$this.removeClass('processing');if(true===response.success){success.removeClass(hidden);mail_input.val('');return 1;}
error.removeClass(hidden).html(response.data.message);return!1;});})},main_menu:function(self,target){var menu=target,duration_timeout,closeSubs,hideSub,showSub,init,moreMenuContent='&middot;&middot;&middot;',imgurl='',srcset='',hasimg=false,hasicon=false,hasprop=Object.prototype.hasOwnProperty;if(hasprop.call(window,'autoclean')&&hasprop.call(window.autoclean,'more_button_options')&&hasprop.call(window.autoclean.more_button_options,'more_button_type')){switch(window.autoclean.more_button_options.more_button_type){case 'image':imgurl=window.autoclean.more_button_options.more_button_image_url;if(window.autoclean.more_button_options.retina_more_button_image_url){srcset=' srcset="'+window.autoclean.more_button_options.retina_more_button_image_url+' 2x"';}
moreMenuContent='<img src="'+imgurl+'"'+srcset+' alt="'+moreMenuContent+'">';hasimg=true;break;case 'icon':moreMenuContent='<i class="fa '+window.autoclean.more_button_options.more_button_icon+'"></i>';hasicon=true;break;case 'text':default:moreMenuContent=window.autoclean.more_button_options.more_button_text||moreMenuContent;hasimg=false;hasicon=false;break;}}
menu.superGuacamole({threshold:768,minChildren:3,childrenFilter:'.menu-item',menuTitle:moreMenuContent,menuUrl:'#',templates:{menu:'<li id="%5$s" class="%1$s'+(hasimg?' super-guacamole__menu-with-image':'')+
(hasicon?' super-guacamole__menu-with-icon':'')+'"><a href="%2$s">%3$s</a><ul class="sub-menu">%4$s</ul></li>',child_wrap:'<ul class="%1$s">%2$s</ul>',child:'<li id="%5$s" class="%1$s"><a href="%2$s">%3$s</a><ul class="sub-menu">%4$s</ul></li>'}});closeSubs=function(){$('.menu-hover > a',menu).each(function(){hideSub($(this));});};hideSub=function(anchor){anchor.parent().removeData('index').removeClass('menu-hover').triggerHandler('close_menu');anchor.siblings('ul').addClass('in-transition');clearTimeout(duration_timeout);duration_timeout=setTimeout(function(){anchor.siblings('ul').removeClass('in-transition');},200);};showSub=function(anchor){var item=anchor.parent();item.siblings().find('.menu-hover').addBack('.menu-hover').children('a').each(function(){hideSub($(this),true);});item.addClass('menu-hover').triggerHandler('open_menu');};init=function(){var $mainNavigation=$('.main-navigation'),$mainMenu=$('ul.menu',$mainNavigation),$menuToggle=$('.menu-toggle[aria-controls="main-menu"]'),$liWithChildren=$('li.menu-item-has-children, li.page_item_has_children',menu),$self;$liWithChildren.hoverIntent({over:function(){showSub($(this).children('a'));},out:function(){if($(this).hasClass('menu-hover')){hideSub($(this).children('a'));}},timeout:300});var $parentNode,$self,index=-1;function doubleClickMenu($jqEvent){$self=$(this);if($self.index()!==parseInt($parentNode.data('index'),10)){$jqEvent.preventDefault();}
$parentNode.data('index',$self.index());}
if('ontouchend'in window){$mainNavigation.find('#main-menu li[class*="children"] > a').on('click',doubleClickMenu);CherryJsCore.variable.$document.on('touchend',function($jqEvent){$parentNode=$($jqEvent.target).parent();if($parentNode.hasClass('menu-hover')===false){closeSubs();index=$parentNode.data('index');if(index){$parentNode.data('index',parseInt(index,10)-1);}}});}
$menuToggle.on('click',function($event){$event.preventDefault();setTimeout(function(){if(!$mainNavigation.hasClass('animate')){$mainNavigation.addClass('animate');}
$mainNavigation.toggleClass('show');$('html').toggleClass('mobile-menu-active');},10);$menuToggle.attr('aria-expanded',!$menuToggle.hasClass('toggled'));$menuToggle.toggleClass('toggled');});};init();},mobile_menu:function(self){var $mainNavigation=$('.main-navigation'),$menuToggle=$('.menu-toggle[aria-controls="main-menu"]');$mainNavigation.find('li.menu-item-has-children > a').after('<a href="#" class="sub-menu-toggle"></a>');function debounce(threshold,callback){var timeout;return function debounced($event){function delayed(){callback($event);timeout=null;}
if(timeout){clearTimeout(timeout);}
timeout=setTimeout(delayed,threshold);};}
function resizeHandler($event){var $window=CherryJsCore.variable.$window,width=$window.outerWidth(true);if(768<=width){$mainNavigation.removeClass('mobile-menu');}else{$mainNavigation.addClass('mobile-menu');}}
function toggleSubMenuHandler($event){var $subMenu=$(this);$subMenu.toggleClass('active');$subMenu.parent().toggleClass('sub-menu-open');}
function toggleMenuHandler($event){var $toggle=$(this);$event.preventDefault();$mainNavigation.toggleClass('active');if($toggle.hasClass('active')){$toggle.removeClass('active');$mainNavigation.find('.sub-menu-open').removeClass('sub-menu-open');}}
resizeHandler();CherryJsCore.variable.$window.on('resize orientationchange',debounce(500,resizeHandler));$mainNavigation.on('click','.sub-menu-toggle',toggleSubMenuHandler);$menuToggle.on('click',toggleMenuHandler);},page_preloader_init:function(self){if($('.page-preloader-cover')[0]){$('.page-preloader-cover').delay(500).fadeTo(500,0,function(){$(this).remove();});}},to_top_init:function(self){if($.isFunction(jQuery.fn.UItoTop)){$().UItoTop({text:autoclean.labels.totop_button,scrollSpeed:600});}},widget_classes_init:function(self){$(document).ready(function(){$('.widget_archive:has( select )').addClass('widget_archive-select');$('.widget_categories:has( select )').addClass('widget_categories-select');$('.widget_text:has( blockquote )').addClass('widget_text_blockquote');});},full_height:function(self){if($('body.page-template-coming-soon-page')[0]){var full_height_section=$('.full-height');if(full_height_section.height()<$(window).height()){var full_height_section_padding=$(window).height()-full_height_section.height();full_height_section.css({'padding-top':full_height_section_padding/2,'padding-bottom':full_height_section_padding/2});}}}}
CherryJsCore.theme_script.init();}(jQuery));